// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "You San Di Technology";
    extern const char* const UnityCopyright = "(c) 2025 You San Di Technology. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/b/o/dev/tj";

    extern const char* const UnityVersion = "2022.3.61t8";
    extern const char* const UnityVersionDigits = "2022.3.61";
    extern const char* const UnityVersionSuffix = "t8";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 61;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.3.61t8_4d1c4dc33c81";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.3.61t8_4d1c4dc33c81";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.3.61t8 (4d1c4dc33c81)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 5053517;

    extern const UInt64 UnityVersionDate = 1760103299;
    extern const char* const UnityVersionBranch = "tuanjie/1.6/staging";
    extern const char* const UnityVersionDisplay = "2022.3.61t8";
    extern const char* const UnityVersionDisplay_Verbose = "2022.3.61t8.git.5053517";
    extern const char* const UnityVersionRevision = "4d1c4dc33c81";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.3.61t8 (4d1c4dc33c81)";
    extern const wchar_t* const L_UnityVersion = L"2022.3.61t8";


    // Tuanjie version
    extern const char* const TuanjieVersion = "1.6.7";
    extern const char* const TuanjieVersionDigits = "1.6.7";
    extern const char* const TuanjieVersionSuffix = "";
    extern const UInt32 TuanjieVersionVer = 1;
    extern const UInt32 TuanjieVersionMajor = 6;
    extern const UInt32 TuanjieVersionMinor = 7;

    extern const char* const TuanjieVersionUnderHash = "1.6.7_4d1c4dc33c81";
    extern const char* const TuanjieVersionUnderHash_Verbose = "1.6.7_4d1c4dc33c81";
    extern const char* const TuanjieVersionUnderHash_WithParens = "1.6.7 (4d1c4dc33c81)";

    extern const char* const TuanjieVersionDisplay = "1.6.7";
    extern const char* const TuanjieVersionDisplay_Verbose = "1.6.7.git.5053517";

    extern const wchar_t* const L_TuanjieVersionUnderHash_WithParens = L"1.6.7 (4d1c4dc33c81)";
    extern const wchar_t* const L_TuanjieVersion = L"1.6.7";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "You San Di Technology"
    #define UNITY_COPYRIGHT "(c) 2025 You San Di Technology. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 61
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.3.61t8_4d1c4dc33c81"
    #define UNITY_VERSION_PARENS_HASH "2022.3.61t8 (4d1c4dc33c81)"
    #define UNITY_VERSION_BLD 5053517
    #define UNITY_VERSION_WIN "2022.3.61.5053517"

    #define TUANJIE_VERSION_VER 1
    #define TUANJIE_VERSION_MAJ 6
    #define TUANJIE_VERSION_MIN 7
    #define TUANJIE_VERSION_UNDER_HASH "1.6.7_4d1c4dc33c81"
    #define TUANJIE_VERSION_PARENS_HASH "1.6.7 (4d1c4dc33c81)"
    #define TUANJIE_VERSION_WIN "1.6.7.5053517"

#endif // !RC_INVOKED
